"""Add profile model

Revision ID: 0bd83cfd6966
Revises: 05a06f658868
Create Date: 2026-08-12 21:29:34.039849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd83cfd6966'
down_revision: Union[str, Sequence[str], None] = '05a06f658868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anketa_number', sa.String(length=16), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('marital_status', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('original_location', sa.String(length=128), nullable=False),
    sa.Column('religion', sa.String(length=128), nullable=False),
    sa.Column('languages_count', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('partner_requirements', sa.Text(), nullable=False),
    sa.Column('filled_by', sa.String(length=32), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('hijab', sa.Boolean(), nullable=True),
    sa.Column('relocation', sa.Boolean(), nullable=True),
    sa.Column('second_wife', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_anketa_number'), 'profiles', ['anketa_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_anketa_number'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
