"""Add vip and search access to User

Revision ID: c2e633ac7f94
Revises: 0bd83cfd6966
Create Date: 2026-08-12 21:35:37.971454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e633ac7f94'
down_revision: Union[str, Sequence[str], None] = '0bd83cfd6966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('search_access', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_access')
    op.drop_column('users', 'vip_expires_at')
    # ### end Alembic commands ###
